# Data-X Spring 2018: Homework 02

### Regression, Classification, Webscraping

**Authors:** Sana Iqbal (Part 1, 2, 3), Alexander Fred-Ojala (Extra Credit)


In this homework, you will do some exercises with prediction-classification, regression and web-scraping.


## Part 1


### Data:
__Data Source__:
Data file is uploaded to bCourses and is named: __Energy.csv__

The dataset was created by Angeliki Xifara ( Civil/Structural Engineer) and was processed by Athanasios Tsanas, Oxford Centre for Industrial and Applied Mathematics, University of Oxford, UK).

__Data Description__:

The dataset contains eight attributes of a building (or features, denoted by X1...X8) and response being the heating load on the building, y1. 

* X1	Relative Compactness 
* X2	Surface Area 
* X3	Wall Area 
*  X4	Roof Area 
*  X5	Overall Height 
* X6	Orientation 
*  X7	Glazing Area 
*  X8	Glazing Area Distribution 
*  y1	Heating Load 


#### Q1:Read the data file in python. Describe data features in terms of type, distribution range and mean values. Plot feature distributions.This step should give you clues about data sufficiency.

In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [78]:
energy = pd.read_csv("Energy.csv")
energy.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84

In [79]:
energy.describe()

X1          X2          X3          X4         X5          X6  \
count  768.000000  768.000000  768.000000  768.000000  768.00000  768.000000   
mean     0.764167  671.708333  318.500000  176.604167    5.25000    3.500000   
std      0.105777   88.086116   43.626481   45.165950    1.75114    1.118763   
min      0.620000  514.500000  245.000000  110.250000    3.50000    2.000000   
25%      0.682500  606.375000  294.000000  140.875000    3.50000    2.750000   
50%      0.750000  673.750000  318.500000  183.750000    5.25000    3.500000   
75%      0.830000  741.125000  343.000000  220.500000    7.00000    4.250000   
max      0.980000  808.500000  416.500000  220.500000    7.00000    5.000000   

               X7         X8          Y1  
count  768.000000  768.00000  768.000000  
mean     0.234375    2.81250   22.307201  
std      0.133221    1.55096   10.090196  
min      0.000000    0.00000    6.010000  
25%      0.100000    1.75000   12.992500  
50%      0.250000    3.00000   18.950000  
75%      0.400000    4.00000   31.667500  
max      0.400000    5.00000   43.100000

In [80]:
x = plt.figure()
x = energy.hist()

 __REGRESSION__:
LABELS ARE CONTINUOUS VALUES.
Here the model is trained to predict a continuous value for each instance.
On inputting a feature vector into the model, the trained model is able to predict a continuous value  for  that instance.  

__Q2.1: Train a linear regression model on 85 percent of the given dataset, what is the intercept value and coefficient values.__



In [92]:
x = energy[['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8']]
y = energy[['Y1']]

In [83]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=100)
print ('Number of samples in training data:',len(x_train))
print ('Number of samples in validation data:',len(x_test))

Number of samples in training data: 652
Number of samples in validation data: 116


In [84]:
from sklearn import linear_model

# Name our logistic regression object
LinearRegressionModel = linear_model.LinearRegression()

# we create an instance of logistic Regression Classifier and fit the data.
print ('Training a logistic Regression Model..')
LinearRegressionModel.fit(x_train, y_train)
y_train_pred = LinearRegressionModel.predict(x_train)
y_test_pred = LinearRegressionModel.predict(x_test)
print('Coefficients:', LinearRegressionModel.coef_)
print('Intercept:', LinearRegressionModel.intercept_)

Training a logistic Regression Model..
Coefficients: [[ -6.09999091e+01  -1.20592151e+11   1.20592151e+11   2.41184302e+11
    4.33188083e+00   1.88790945e-02   2.00671334e+01   2.35574595e-01]]
Intercept: [ 75.75107745]



#### Q.2.2: Report model performance using 'ROOT MEAN SQUARE' error metric on:  
__1. Data that was used for training(Training error)__   
__2. On the 15 percent of unseen data (test error) __ 



In [85]:
from sklearn.metrics import mean_squared_error
train_rmse = mean_squared_error(y_train, y_train_pred)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error:', train_rmse, 'Testing Error:', test_rmse)

Training Error: 8.57694489763 Testing Error: 8.27772712612



__ Q2.3: Lets us see the effect of amount of data on the performance of prediction model.Use varying amounts of  Training data (100,200,300,400,500,all) to train regression models and report  training error and validation error in each case. Validation data/Test data   is the same as above for  all  these cases.__  

Plot error rates vs number of training examples.Comment on the relationshipyou observe in the plot, between the amount of data used to train the model and the validation accuracy of the model.

__Hint:__ Use array indexing to choose varying data amounts

In [98]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_100 = x.iloc[0:100,:]
y_train_100 = y.head(100)
LinearRegressionModel.fit(x_train_100, y_train_100)
y_train_pred_100 = LinearRegressionModel.predict(x_train_100)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_100, y_train_pred_100)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 6.9491634109 Testing Error: 79.0636990049


In [99]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_200 = x.iloc[0:200,:]
y_train_200 = y.head(200)
LinearRegressionModel.fit(x_train_200, y_train_200)
y_train_pred_200 = LinearRegressionModel.predict(x_train_200)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_200, y_train_pred_200)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 6.87483688534 Testing Error: 77.9965754862


In [100]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_300 = x.iloc[0:300,:]
y_train_300 = y.head(300)
LinearRegressionModel.fit(x_train_300, y_train_300)
y_train_pred_300 = LinearRegressionModel.predict(x_train_300)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_300, y_train_pred_300)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 7.11325122622 Testing Error: 36.5033093621


In [101]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_400 = x.iloc[0:400,:]
y_train_400 = y.head(400)
LinearRegressionModel.fit(x_train_400, y_train_400)
y_train_pred_400 = LinearRegressionModel.predict(x_train_400)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_400, y_train_pred_400)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 8.26707234968 Testing Error: 11.5576597351


In [102]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_500 = x.iloc[0:500,:]
y_train_500 = y.head(500)
LinearRegressionModel.fit(x_train_500, y_train_500)
y_train_pred_500 = LinearRegressionModel.predict(x_train_500)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_500, y_train_pred_500)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 8.7627346608 Testing Error: 9.4596559659


In [103]:
LinearRegressionModel = linear_model.LinearRegression()
x_train_all = x
y_train_all = y
LinearRegressionModel.fit(x_train_all, y_train_all)
y_train_pred_all = LinearRegressionModel.predict(x_train_all)
y_test_pred = LinearRegressionModel.predict(x_test)

train_rmse = mean_squared_error(y_train_all, y_train_pred_all)
test_rmse = mean_squared_error(y_test, y_test_pred)
print('Training Error', train_rmse, 'Testing Error:', test_rmse)

Training Error 8.51989250663 Testing Error: 8.17136398311



__CLASSIFICATION__:
LABELS ARE DISCRETE VALUES.
Here the model is trained to classify each instance into a set of predefined  discrete classes.
On inputting a feature vector into the model, the trained model is able to predict a  class of that instance. You can also output the probabilities of an instance belnging to a class.  

__ Q 3.1:  Bucket values of 'y1' i.e 'Heating Load'  from the original dataset into 3 classes:__ 

0: 'Low' ( < 15),   
1: 'Medium'  (15-30),   
2: 'High'  (>30)

This converts the given dataset  into a classification problem, classes being, Heating load is: *low, medium or high*. Use this datset with transformed 'heating load' for creating a  logistic regression classifiction model that predicts heating load type of a building. Use test-train split ratio of 0.15.  

*Report training and test accuracies and  confusion matrices.*


**HINT:** Use pandas.cut

In [154]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import accuracy_score, confusion_matrix
y_new = y['Y1']
y_new = pd.cut(y_new, [0, 15, 30, 45], labels=["Low", "Medium", "High"])
y_new = y_new.to_frame()
x_train, x_test, y_new_train, y_new_test = train_test_split(x, y_new, test_size=0.15, random_state=100)
LogisticRegressionModel = linear_model.LogisticRegression()
LogisticRegressionModel.fit(x_train, y_new_train)
y_new_train_pred = LogisticRegressionModel.predict(x_train)
y_new_test_pred = LogisticRegressionModel.predict(x_test)
train_accuracy = accuracy_score(y_new_train, y_new_train_pred)
test_accuracy = accuracy_score(y_new_test, y_new_test_pred)
print('Training Accuracy', train_accuracy, 'Testing Accuracy:', test_accuracy)
train_cf = confusion_matrix(y_new_train, y_new_train_pred)
test_cf = confusion_matrix(y_new_test, y_new_test_pred)
print('Training Confusion Matrix:', '\n', train_cf, '\n', 'Testing Confusion Matrix:', '\n', test_cf)

Training Accuracy 0.773006134969 Testing Accuracy: 0.76724137931
Training Confusion Matrix: 
 [[140   0  35]
 [  0 244   1]
 [ 41  71 120]] 
 Testing Confusion Matrix: 
 [[20  0  6]
 [ 0 40  0]
 [ 9 12 29]]


__ Q3.2: One of the preprocessing steps in Data science is Feature Scaling i.e getting all our data on the same scale by setting same  Min-Max of feature values. This makes training less sensitive to the scale of features . Scaling is important in algorithms that use distance based classification, SVM or K means or involve gradient descent optimization.If we  Scale features in the range [0,1] it is called unity based normalization.__

__Perform unity based normalization on the above dataset and train the model again, compare model performance in training and validation with your previous model.__  

refer:http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing-scaler  
more at: https://en.wikipedia.org/wiki/Feature_scaling

In [161]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_train_minmax = min_max_scaler.fit_transform(x_train)
y_train_minmax = min_max_scaler.fit_transform(y_train)
x_test_minmax = min_max_scaler.fit_transform(x_test)
y_test_minmax = min_max_scaler.fit_transform(y_test)
LinearRegressionModel.fit(x_train_minmax, y_train_minmax)
y_train_minmax_pred = LinearRegressionModel.predict(x_train_minmax)
y_test_minmax_pred = LinearRegressionModel.predict(x_test_minmax)
train_minmax_rmse = mean_squared_error(y_train_minmax, y_train_minmax_pred)
test_minmax_rmse = mean_squared_error(y_test_minmax, y_test_minmax_pred)
print('Training Error:', train_minmax_rmse, 'Testing Error', test_minmax_rmse)

Training Error: 0.00623261874897 Testing Error 0.00630161185159


## Part 2



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. Analyze the data features, check for NaN values. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 

__ 2. Preprocess data to replace NaN values in a feature(if any) using mean of the feature.  
Train  logistic regression, SVM, perceptron, kNN, xgboost and random forest models using this preprocessed data with 20% test split.Report training and test accuracies.__







In [207]:
diabetes = pd.read_csv('diabetesdata.csv')
diabetes_orig = diabetes
diabetes.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1



__3. What is the  ratio of diabetic persons in 3 equirange bands of 'BMI' and 'Pedigree' in the provided dataset.__

 __Convert these features - 'BP','insulin','BMI' and 'Pedigree'   into categorical values by mapping different bands of values of these features to integers 0,1,2.__  
 
HINT: USE pd.cut with bin=3 to create 3 bins






In [208]:
diabetes['BP'] = pd.cut(diabetes['BP'], 3, labels=[0, 1, 2])
diabetes['insulin'] = pd.cut(diabetes['insulin'], 3, labels=[0, 1, 2])
diabetes['BMI'] = pd.cut(diabetes['BMI'], 3, labels=[0, 1, 2])
diabetes['Pedigree'] = pd.cut(diabetes['Pedigree'], 3, labels=[0, 1, 2])
diabetes.head()

TimesPregnant  glucoseLevel BP insulin BMI Pedigree   Age  IsDiabetic
0              6         148.0  1       0   1        0  50.0           1
1              1           NaN  1       0   1        0  31.0           0
2              8         183.0  1       0   1        0   NaN           1
3              1           NaN  1       0   1        0  21.0           0
4              0         137.0  0       0   1        2  33.0           1


__4. Now consider the original dataset again, instead of generalizing the NAN values with the mean of the feature we will try assigning values to NANs based on some hypothesis. For example for age we assume that the relation between BMI and BP of people is a reflection of the age group.We can have 9 types of BMI and BP relations and our aim is to find the median age of each of that group:__

Your Age guess matrix will look like this:  

| BMI | 0       | 1      | 2  |
|-----|-------------|------------- |----- |
| BP  |             |              |      |
| 0   | a00         | a01          | a02  |
| 1   | a10         | a11          | a12  |
| 2   | a20         | a21          |  a22 |


__Create a guess_matrix  for NaN values of *'Age'* ( using 'BMI' and 'BP')  and  *'glucoseLevel'*  (using 'BP' and 'Pedigree') for the given dataset and assign values accordingly to the NaNs in 'Age' or *'glucoseLevel'* .__


Refer to how we guessed age in the titanic notebook in the class.



In [209]:
guess_ages = np.zeros((3,3), dtype=int)

for idx,dataset in enumerate(diabetes):
    for i in range(0, 3):
        for j in range(0,3):
            guess_df = diabetes[(diabetes.BP == i)&(diabetes.BMI == j)]['Age'].dropna()

            # Extract the median age for this group
            # (less sensitive) to outliers
            age_guess = guess_df.median()
          
            # Convert random age float to int
            guess_ages[i,j] = int(age_guess)
    
    for i in range(0, 3):
        for j in range(0, 3):
            diabetes.loc[ (diabetes.Age.isnull()) & (diabetes.BP == i) & (diabetes.BMI == j),\
                    'Age'] = guess_ages[i,j]

    diabetes['Age'] = diabetes['Age'].astype(int)
print('Guess_Age table:\n',guess_ages)

Guess_Age table:
 [[24 29 33]
 [25 29 32]
 [55 37 31]]


In [212]:
guess_gl = np.zeros((3,3), dtype=int)

for idx,dataset in enumerate(diabetes):
    for i in range(0, 3):
        for j in range(0,3):
            guess_df = diabetes[(diabetes.BP == i)&(diabetes.Pedigree == j)]['glucoseLevel'].dropna()

            # Extract the median age for this group
            # (less sensitive) to outliers
            gl_guess = guess_df.median()
          
            # Convert random age float to int
            guess_gl[i,j] = int(gl_guess)
    
    for i in range(0, 3):
        for j in range(0, 3):
            diabetes.loc[ (diabetes.glucoseLevel.isnull()) & (diabetes.BP == i) & (diabetes.Pedigree == j),\
                    'glucoseLevel'] = guess_gl[i,j]

    diabetes['glucoseLevel'] = diabetes['glucoseLevel'].astype(int)
print('Guess_glucoseLevel table:\n',guess_gl)

Guess_glucoseLevel table:
 [[115 127 137]
 [112 115 149]
 [133 129 159]]




__5. Now, convert 'glucoseLevel' and 'Age' features also to categorical variables of 5 categories each.__

__Use this dataset (with all features in categorical form) to train perceptron, logistic regression and random forest models using 20% test split. Report training and test accuracies.__







In [215]:
diabetes.head()

TimesPregnant glucoseLevel BP insulin BMI Pedigree Age  IsDiabetic
0              6            3  1       0   1        0   2           1
1              1            2  1       0   1        0   0           0
2              8            4  1       0   1        0   0           1
3              1            2  1       0   1        0   0           0
4              0            3  0       0   1        2   0           1

In [236]:
diabetes['Age'] = pd.cut(diabetes['Age'], 5, labels=[0, 1, 2, 3, 4])
diabetes['glucoseLevel'] = pd.cut(diabetes['glucoseLevel'], 5, labels=[0, 1, 2, 3, 4])
diabetes_x = diabetes[['TimesPregnant', 'glucoseLevel', 'BP', 'insulin', 'BMI', 'Pedigree', 'Age']]
diabetes_y = diabetes[['IsDiabetic']]
x_train, x_test, y_train, y_test = train_test_split(diabetes_x, diabetes_y, test_size = 0.2)
PerceptronModel = linear_model.Perceptron()
PerceptronModel.fit(x_train, y_train)
y_train_pred_perc = PerceptronModel.predict(x_train)
y_test_pred_perc = PerceptronModel.predict(x_test)
train_accuracy_perc = accuracy_score(y_train, y_train_pred_perc)
test_accuracy_perc = accuracy_score(y_test, y_test_pred_perc)
print('Perceptron Training Accuracy:', train_accuracy_perc, 'Perceptron Testing Accuracy', test_accuracy_perc)
LogisticModel = linear_model.LogisticRegression()
LogisticModel.fit(x_train, y_train)
y_train_pred_log = LogisticModel.predict(x_train)
y_test_pred_log = LogisticModel.predict(x_test)
train_accuracy_log = accuracy_score(y_train, y_train_pred_log)
test_accuracy_log = accuracy_score(y_train, y_train_pred_log)
print('Logistic Regression Training Accuracy:', train_accuracy_log, 'Logistic Regression Testing Accuracy', test_accuracy_log)
from sklearn.ensemble import RandomForestClassifier
RandomForestModel = RandomForestClassifier()
RandomForestModel.fit(x_train, y_train)
y_train_pred_rf = RandomForestModel.predict(x_train)
y_test_pred_rf = RandomForestModel.predict(x_test)
train_accuracy_rf = accuracy_score(y_train, y_train_pred_rf)
test_accuracy_rf = accuracy_score(y_test, y_test_pred_rf)
print('Random Forest Training Accuracy:', train_accuracy_rf, 'Random Forest Testing Accuracy', test_accuracy_rf)

Perceptron Training Accuracy: 0.648208469055 Perceptron Testing Accuracy 0.662337662338
Logistic Regression Training Accuracy: 0.750814332248 Logistic Regression Testing Accuracy 0.750814332248
Random Forest Training Accuracy: 0.892508143322 Random Forest Testing Accuracy 0.681818181818


### Part 3

1. __Derive the expression for the optimal parameters in the linear regression equation, i.e. solve the normal equation for Ordinary Least Squares for the case of Simple Linear Regression, when we only have one input and one output__

Given a set of _n_ points $(X_i,Y_i)$ where $Yi$ is dependent on $Xi$ by a linear relation,  find the best-fit line,$$Z_i = {aX_i + b}$$  that minimizes the __sum of squared errors in Y__,i.e: $$minimize \sum_{i}{(Y_i- Z_i)^2}$$
__i. __ Show that $$ intercept \quad b = \overline{Y}-  a.\overline{X}\quad  and   \quad slope \quad a= \frac{\sum_{i}(X_i- \overline{X})(Y_i- \overline{Y})}{ \sum_{i}(X_i- \overline{X})^2}$$


 where $\overline{X}$ and  $\overline{Y}$ are the averages of the X values and the Y values, respectively.
 
__ ii. __Show that slope _a_ can be written as $ a = r.(S_y /S_x)$ where $S_y$  = the standard deviation of the Y values and $S_x$= the standard deviation of the X values and _r_ is the correlation coefficient.

##### Please try to write a nice LateXed version of your answer, and do the derivations of the expressions as nicely as possible


_____

i. To minimize the sum of squared errors, $$\sum_{i}{(Y_i- Z_i)^2}$$ we know that there must be some relation between the means of both X and Y to their respective values, as the mean value will reduce the square-error the most. We can simply take the partial derivative of this function with respect to a, the parameter which we are trying to find, and we are left with $$\sum_{i}{(-2X_i*Y_i+(2*a*X_i)^2)}$$ Now we simply seperate and solve for a, which yields $$a = \frac{\sum_{i}{(X_i- X)(Y_i- Y)}}{\sum_{i}{(X_i- X)^2}}$$ The intercept is where the line starts from, and that will simply be $$ b = Y_i - a*X_i$$ after simply rearranging the terms from the linear expression and realizing that $$ Z_i = mean(Y_i)$$ due to the fact that the mean reduces the squared error the most $$\frac{\sum_{i}{Y_i}}{n}$$ where n is the total number of terms in Y. 

ii. r is the correlation coefficient which measures how strong the relationship between the X and Y values are. However, this value is regularized to be between -1 and 1, and thus to account for spread given that the data itself is most probably not regularized, we must scale the correlation coefficient r back up by the standard deviation of the slope which we divided the correlation by earlier to get r, which is indeed $$\frac{S_y}{S_x}$$ Putting these 2 together and rescaling r back up, we get that the slope is equivalent to $$ r * \frac{S_y}{S_x}$$


# Two Extra Credit Points: Fun with Webscraping & Text manipulation
### (Mandatory for Grad students!)

<div class='alert alert-info'> `NOTE:` **If you are a Graduate Section student (enrolled in 290), the Extra Credit Questions are mandatory.**</div>

## 1. Statistics in Presidential Debates

Your first task is to scrape Presidential Debates from the Commission of Presidential Debates website: http://www.debates.org/index.php?page=debate-transcripts.

To do this, you are not allowed to manually look up the URLs that you need, instead you have to scrape them. The root url to be scraped is the one listed above, namely: http://www.debates.org/index.php?page=debate-transcripts


1. By using `requests` and `BeautifulSoup` find all the links / URLs on the website that links to transcriptions of **First Presidential Debates** from the years [2012, 2008, 2004, 2000, 1996, 1988, 1984, 1976, 1960]. In total you should find 9 links / URLs tat fulfill this criteria.
2. When you have a list of the URLs your task is to create a Data Frame with some statistics (see example of output below):
    1. Scrape the title of each link and use that as the column name in your Data Frame. 
    2. Count how long the transcript of the debate is (as in the number of characters in transcription string). Feel free to include `\` characters in your count, but remove any breakline characters, i.e. `\n`. You will get credit if your count is +/- 10% from our result.
    3. Count how many times the word **war** was used in the different debates. Note that you have to convert the text in a smart way (to not count the word **warranty** for example, but counting **war.**, **war!**, **war,** or **War** etc.
    4. Also scrape the most common used word in the debate, and write how many times it was used. Note that you have to use the same strategy as in 3 in order to do this.
    
**Tips:**

___

In order to solve question 3 and 4 above it can be useful to work with Regular Expressions and explore methods on strings like `.strip(), .replace(), .find(), .count(), .lower()` etc. Both are very powerful tools to do string processing in Python. To count common words for example I used a `Counter` object and a Regular expression pattern for only words, see example:

```python
    from collections import Counter
    import re

    counts = Counter(re.findall(r"[\w']+", text.lower()))
```

Read more about Regular Expressions here: https://docs.python.org/3/howto/regex.html
    
    
**Example output of all of the answers to EC Question 1:**


![pres_stats](https://github.com/ikhlaqsidhu/data-x/raw/master/x-archive/misc/hw2_imgs_spring2018/president_stats.png)




----

.




    
## 2. Download and read in specific line from many data sets

Scrape the first 27 data sets from this URL http://people.sc.fsu.edu/~jburkardt/datasets/regression/ (i.e.`x01.txt` - `x27.txt`). Then, save the 5th line in each data set, this should be the name of the data set author (get rid of the `#` symbol, the white spaces and the comma at the end). 

Count how many times (with a Python function) each author is the reference for one of the 27 data sets. Showcase your results, sorted, with the most common author name first and how many times he appeared in data sets. Use a Pandas DataFrame to show your results, see example.

**Example output of the answer EC Question 2:**

![author_stats](https://github.com/ikhlaqsidhu/data-x/raw/master/x-archive/misc/hw2_imgs_spring2018/data_authors.png)
